# Generated by Django 5.0.4 on 2024-04-29 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCP', '0002_remove_tasks_end_date_tasks_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
