# Generated by Django 5.0.4 on 2024-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCP', '0004_remove_tasks_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='person',
            field=models.CharField(choices=[('Chetan Pagare', 'Chetan Pagare'), ('Hari', 'Hari'), ('Saranya', 'Saranya')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tags',
            field=models.CharField(choices=[('backend task', 'backend task'), ('frontend task', 'frontend task'), ('Testing', 'Testing')], max_length=255),
        ),
    ]
